budget_manager/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('explore/', include('DBExplorer.urls'))
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('', views.main, name='main'),
    path('report', views.report, name='report'),
    path('history', views.history, name='history'),
    path('edit/<int:id>/<str:type>', views.edit, name='edit')
]

core/forms/CustomDateInput.py
from django import forms


class CustomDateInput(forms.DateInput):
    input_type = 'date'

core/forms/ExpenseForm.py
from django import forms
from .CustomDateInput import CustomDateInput
from django.utils.translation import gettext as _
from django.core.exceptions import ValidationError
from .utils import get_account_choices, get_expense_category_choices

from itertools import chain
from datetime import date


class ExpenseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    amount_exp = forms.FloatField(
        min_value=0,
        label='Сумма',
        widget=forms.NumberInput(attrs={
            'placeholder': 'Сумма'
        })
    )

    from_cat = forms.ChoiceField(
        label='В',
        choices=[(-1, "Откуда...")] + get_account_choices(),
        widget=forms.Select()
    )

    to_cat = forms.ChoiceField(
        label='Из',
        choices=[(-1, "Куда...")] + list(chain(
            get_expense_category_choices(),
            get_account_choices()
        )),
        widget=forms.Select()
    )

    when = forms.DateField(label='Дата', widget=CustomDateInput(attrs={
                'value': date.today()
    }))

    commentary_exp = forms.CharField(
        label='Комментарий',
        required=False,
        widget=forms.Textarea(attrs={
                'placeholder': 'Комментарий'
        })
    )

    def clean_amount(self):
        data = self.cleaned_data['amount']
        decimal_part = str(data*100).split('.')[1]

        if len(decimal_part) > 1 or int(decimal_part) != 0:
            self.fields['amount'].widget.attrs.update({
                'class': 'form-control is-invalid'
            })
            raise ValidationError(_('Неверный формат суммы'))

        return data

    def clean_from_cat(self):
        data = self.cleaned_data['from_cat']

        if data == '-1':
            self.fields['from_cat'].widget.attrs.update({
                'class': 'form-control is-invalid'
            })
            raise ValidationError(
                _('Выберите откуда'),
                code='invalid'
            )

        return data

    def clean_to_cat(self):
        data = self.cleaned_data['to_cat']

        if data == '-1':
            self.fields['to_cat'].widget.attrs.update({
                'class': 'form-control is-invalid'
            })
            raise ValidationError(_('Выберите куда потрачено'), code='invalid')

        return data

    def clean(self):
        cleaned_data = super().clean()

        from_data = cleaned_data.get('from_cat')
        to_data = cleaned_data.get('to_cat')

        if from_data == to_data:
            # Пытаемся перевести деньги на то же место хранения
            self.fields['from_cat'].widget.attrs.update({
                'class': 'form-control is-invalid'
            })
            self.fields['to_cat'].widget.attrs.update({
                'class': 'form-control is-invalid'
            })
            raise ValidationError(
                _('Выберите разные места хранения'),
                code='invalid'
            )

core/forms/IncomeForm.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _
from .CustomDateInput import CustomDateInput
from .utils import get_account_choices, get_income_category_choices

from itertools import chain
from datetime import date


class IncomeForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    amount = forms.FloatField(
        min_value=0,
        label='Сумма',
        widget=forms.NumberInput(attrs={
            'placeholder': 'Сумма'
        })
    )

    from1 = forms.ChoiceField(
        label='Из',
        choices=[(-1, "Откуда...")] + list(chain(
            get_income_category_choices(),
            get_account_choices()
        ))
    )

    to = forms.ChoiceField(
        label='В',
        choices=[(-1, "Куда...")] + get_account_choices(),
        widget=forms.Select(attrs={
                'placeholder': 'Куда'
        })
    )

    date = forms.DateField(label='Дата', widget=CustomDateInput(attrs={
                'value': date.today()
    }))

    commentary = forms.CharField(
        label='Комментарий',
        required=False,
        widget=forms.Textarea(attrs={
                'placeholder': 'Комментарий'
        })
    )

    def clean_amount(self):
        data = self.cleaned_data['amount']
        decimal_part = str(data*100).split('.')[1]

        if len(decimal_part) > 1 or int(decimal_part) != 0:
            self.fields['amount'].widget.attrs.update({
                'class': 'form-control is-invalid'
            })
            raise ValidationError(_('Неверный формат суммы'))

        return data

    def clean_from1(self):
        data = self.cleaned_data['from1']

        if data == '-1':
            self.fields['from1'].widget.attrs.update({
                'class': 'form-control is-invalid'
            })
            raise ValidationError(_('Выберите откуда пришло'), code='invalid')

        return data

    def clean_to(self):
        data = self.cleaned_data['to']

        if data == '-1':
            self.fields['to'].widget.attrs.update({
                'class': 'form-control is-invalid'
            })
            raise ValidationError(_('Выберите куда начислить'), code='invalid')

        return data

    def clean(self):
        cleaned_data = super().clean()

        from_data = cleaned_data.get('from1')
        to_data = cleaned_data.get('to')

        if from_data == to_data:
            # Пытаемся перевести деньги на то же место хранения
            self.fields['from1'].widget.attrs.update({
                'class': 'form-control is-invalid'
            })
            self.fields['to'].widget.attrs.update({
                'class': 'form-control is-invalid'
            })
            raise ValidationError(
                _('Выберите разные места хранения'),
                code='invalid'
            )

core/forms/utils.py
from core.models import Account, ExpenseCategory, IncomeCategory


def get_account_choices():
    account_choices = []

    for account in Account.objects.all():
        account_choices.append(('acc__' + str(account.id), account.name))

    return account_choices


def get_income_category_choices():
    category_choices = []

    for category in IncomeCategory.objects.all():
        category_choices.append(('cat__' + str(category.id), category.name))

    return category_choices


def get_expense_category_choices():
    category_choices = []

    for category in ExpenseCategory.objects.all():
        category_choices.append(('cat__' + str(category.id), category.name))

    return category_choices

core/views.py
from django.shortcuts import render
from .forms.IncomeForm import IncomeForm
from .forms.ExpenseForm import ExpenseForm
import core.utils as utils
from .models import IncomeTransaction, ExpenseTransaction, InnerTransaction
from django.http import HttpResponseRedirect

import datetime

def edit(request,id,type):
    id_transaction=id
    transaction_type=type
    transaction=None
    
    if transaction_type == "IncomeTransaction":
        transaction = IncomeTransaction.objects.get(id=id_transaction)
    if transaction_type == "ExpenseTransaction":
        transaction = ExpenseTransaction.objects.get(id=id_transaction)
    if transaction_type == "InnerTransaction":
        transaction = InnerTransaction.objects.get(id=id_transaction)

    if len(str(transaction.date.month)) == 1:
        transaction_date_month_for_input = "0" + str(transaction.date.month)
    else:
        transaction_date_month_for_input = transaction.date.month

    if len(str(transaction.date.day)) == 1:
        transaction_date_day_for_input = "0" + str(transaction.date.day)
    else:
        transaction_date_day_for_input = transaction.date.day


    if request.method == 'POST':
        if transaction_type == "IncomeTransaction":#если получили type доход
            transaction.amount = float(request.POST.get("amount"))*100
            transaction.commentary = request.POST.get("commentary")
            transaction.date = request.POST.get("when")
            transaction.account_id = int(request.POST.get("account"))
            transaction.income_category_id = int(request.POST.get("category"))
            transaction.save()
            return HttpResponseRedirect("/history")

        if transaction_type == "ExpenseTransaction":#если получили type расход
            transaction.amount = float(request.POST.get("amount"))*100
            transaction.commentary = request.POST.get("commentary")
            transaction.date = request.POST.get("when")
            transaction.account_id = int(request.POST.get("account"))
            transaction.expense_category_id = int(request.POST.get("category"))
            transaction.save()
            return HttpResponseRedirect("/history")
        
        if transaction_type == "InnerTransaction":#если получили type внутренние 
            transaction.amount = float(request.POST.get("amount"))*100
            transaction.commentary = request.POST.get("commentary")
            transaction.date = request.POST.get("when")
            transaction.account_from_id = int(request.POST.get("account_from_id"))
            transaction.account_to_id = int(request.POST.get("account_to_id"))
            transaction.save()
            return HttpResponseRedirect("/history")

    return render(request,'core/edit.html',{'transaction': transaction, 'id_transaction':id_transaction, 'transaction_type':transaction_type, 'transaction_date_month_for_input':transaction_date_month_for_input, 'transaction_date_day_for_input':transaction_date_day_for_input})
    

def main(request):
    visible_form = 'expense'

    # Обработка формы
    formEF = ExpenseForm()
    formIF = IncomeForm()
    if request.method == 'POST':
        if request.POST['form'] == "incf":
            formIF = IncomeForm(request.POST)
            visible_form = 'income'

            if formIF.is_valid():
                utils.post_income_transaction(formIF.cleaned_data)
                formIF = IncomeForm()
        elif request.POST['form'] == "expf":
            formEF = ExpenseForm(request.POST)
            visible_form = 'expense'
            if formEF.is_valid():
                utils.post_expense_transaction(formEF.cleaned_data)
                formEF = ExpenseForm()

    url_name = request.resolver_match.url_name

    return render(request, 'core/main.html', {
        'account_list': utils.get_account_list(),
        'latest_transactions': utils.get_current_week_transactions(),
        'url_name': url_name,
        'income_form': formIF,
        'expence_form': formEF,
        'visible_form': visible_form,
        'expenses': utils.get_expenses_for_this_month()
    })


def report(request):
    url_name = request.resolver_match.url_name

    now = datetime.datetime.now()
    month_filter = now.month  # Значение месяца по умолчанию для фильра по месяцу и году
    year_filter = now.year  # Значение года по умолчанию для фильра по месяцу и году
    monthDict = utils.get_month()  # Получение всех месяцев и годов существующих транзакций

    if request.method == 'POST':  # Если пользователь воспользовался фильтром
        if request.POST.get('month_filter_report'):  # Если пользователь применил фильтр по месяцу и году
            month_year_filter = utils.get_month_year_filter(request.POST.get('month_filter_report'))  # Получение значения фильтра по месяцам и годам в виде пары (month, year)
            month_filter = month_year_filter[0]  # Получение значения месяца из пары (month, year)
            year_filter = month_year_filter[1]  # Получение значения года из пары (month, year)

            IncomeCategoriesSummDict = utils.get_income_categories_name_and_amount(month_filter, year_filter)
            ExpenseCategoriesSummDict = utils.get_expense_categories_name_and_amount(month_filter, year_filter)
            transactions = utils.get_all_transaction_with_month_and_year_filter(year_filter, month_filter)  # Получение всех существующих транзакций с учетом фильтра по месяцам и годам
            return render(request, 'core/report.html', {
                'url_name': url_name,
                'month_filter': month_filter,
                'year_filter': year_filter,
                'monthDict': monthDict,
                'IncomeCategoriesSummDict': IncomeCategoriesSummDict,
                'ExpenseCategoriesSummDict': ExpenseCategoriesSummDict,
                'expenses': utils.get_expenses_for_filter_month(
                    month_filter,
                    year_filter
                ),
                'incomes': utils.get_incomes_for_filter_month(
                    month_filter,
                    year_filter
                ),
                'transactions': transactions
            })

    IncomeCategoriesSummDict = utils.get_income_categories_name_and_amount(
        month_filter,
        year_filter
    )
    ExpenseCategoriesSummDict = utils.get_expense_categories_name_and_amount(
        month_filter,
        year_filter
    )
    transactions = utils.get_all_transaction_with_month_and_year_filter(
        year_filter,
        month_filter
    )  # Получение всех существующих транзакций с учетом фильтра по месяцам и годам

    return render(request, 'core/report.html', {
        'url_name': url_name,
        'month_filter': month_filter,
        'year_filter': year_filter,
        'monthDict': monthDict,
        'IncomeCategoriesSummDict': IncomeCategoriesSummDict,
        'ExpenseCategoriesSummDict': ExpenseCategoriesSummDict,
        'expenses': utils.get_expenses_for_filter_month(month_filter, year_filter),
        'incomes': utils.get_incomes_for_filter_month(month_filter, year_filter),
        'transactions': transactions
    })


def history(request):
    url_name = request.resolver_match.url_name  # Получение имени активной страницы

    now = datetime.datetime.now()
    month_filter = now.month  # Значение месяца по умолчанию для фильра по месяцу и году
    year_filter = now.year  # Значение года по умолчанию для фильра по месяцу и году
    income_category = None  # Значение фильтра по категориям дохода
    expense_category = None  # Значение фильтра по категориям расхода

    if request.method == 'POST':  # Если пользователь воспользовался любым фильтром или удалением транзакции           

        if request.POST.get('IncomeTransactionId'):  # Если пользователь воспользовался удалением транзакции дохода
            utils.delete_transaction(
                request,
                request.POST.get('IncomeTransactionId')
            )  # Удаление транзакции дохода

        if request.POST.get('InnerTransactionId'):  # Если пользователь воспользовался удалением внутренней транзакции
            utils.delete_transaction(
                request,
                request.POST.get('InnerTransactionId')
            )  # Удаление внутренней транзакции

        if request.POST.get('ExpenseTransactionId'):  # Если пользователь воспользовался удалением транзакции расхода
            utils.delete_transaction(
                request,
                request.POST.get('ExpenseTransactionId')
            )  # Удаление транзакции расхода

        if request.POST.get('month_filter_history'):  # Если пользователь применил фильтр по месяцу и году
            month_year_filter = utils.get_month_year_filter(
                request.POST.get('month_filter_history')
            )  # Получение значения фильтра по месяцам и годам в виде пары (month, year)
            month_filter = month_year_filter[0]  # Получение значения месяца из пары (month, year)
            year_filter = month_year_filter[1]  # Получение значения года из пары (month, year)

            if request.POST.get('income_filter_history') == 'income filter inner':  # Если в фильтре категориях дохода выбрано значение "Внутренние переводы"
                expense_category = None
                income_category = request.POST.get('income_filter_history')  # Получение значения фильтра по категориям дохода
                transactions = utils.get_inner_transaction_with_month_and_year_filter(year_filter, month_filter)  # Получение всех внутренних транзакций с учетом фильтра по месяцам и годам

                monthDict = utils.get_month()  # Получение всех месяцев и годов существующих транзакций
                incomeCategoriesDict = utils.get_income_categories()  # Получение всех категорий дохода в существующих транзакциях
                expenseCategoriesDict = utils.get_expense_categories()  # Получение всех категорий расхода в существующих транзакциях

                return render(

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    
    <!-- fontawesome CSS -->
    <link
      rel="stylesheet"
      href="{% static 'vendor/fontawesome/css/all.min.css' %}"
      type="text/css"
    />

    <!-- Custom CSS -->
    <link href="{% static 'css/core.css' %}" rel="stylesheet" type="text/css"/>
  </head>

  <body>
    <div class="container-fluid pl-0">
      <div class="row">
        <div class="col-md-2">
          <aside>
              <a href="{% url 'core:main' %}">
                <img class ="logo" src="{% static 'img/main_logo.png' %}" loading="lazy">
              </a></br>
              <a class="nav-link fas fa-home {% if url_name == 'main' %}active{% endif %}" href="{% url 'core:main' %}"> Главная страница</a></br>
              <a class="nav-link fas fa-file-invoice-dollar {% if url_name == 'history' %}active{% endif %}" href="{% url 'core:history' %}"> История операций</a></br>
              <a class="nav-link fas fa-chart-pie {% if url_name == 'report' %}active{% endif %}" href="{% url 'core:report' %}"> Отчет</a></br>
          </aside>
        </div>
        
        <div class="col-md-10">
          {% block content %}
          {% endblock %}
        </div>
      </div>
      
    </div>
    

    <!-- Bootstrap core JavaScript -->
    <script
      type="text/javascript"
      src="{% static 'vendor/jquery/jquery.min.js' %}"
    ></script>
    <script
      type="text/javascript"
      src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"
    ></script>
    <!-- Google charts JS -->
    <script
      type="text/javascript"
      src="{% static 'vendor/google-charts/js/loader.js' %}"
    ></script>

    {% block javascript %}
    {% endblock %}
  </body>
</html>

core/templates/core/base_form.html
<!-- {{ form.non_field_errors }} -->

{% for field in form %}
  {% if field.name != 'commentary' and field.name != 'commentary_exp'%}
    <div class="field-narrow">
      {{ field }}
      <div class="invalid-feedback">
        {{ field.errors }}
      </div>
    </div>
  {% endif%}

  {% if field.name == 'commentary' or field.name == 'commentary_exp' %}
    <div class="field-wide">
      {{ field }}
      <div class="invalid-feedback">
        {{ field.errors }}
      </div>
    </div>
  {% endif %}
{% endfor %}

<input type="submit" class="btn btn-primary" value="Отправить">

core/templates/core/history.html
{% extends 'core/base.html' %}
{% load core_custom_tags %}
{% load static %}

{% block title %}История{% endblock %}

{% block content %}

  <h1 class="text-center my-4">История</h1>
  <div class="row justify-content-center">
    <div class="col-md-10">
      <form id="history-page__month-and-categories-filter" method="POST" action="{% url 'core:history' %}">
        {% csrf_token %}
        <div class="row justify-content-center align-items-center">
          <div class="col-lg-2 col-md-5">
            <select class="form-control form-control-sm" name="month_filter_history" onchange="this.form.submit()">
              <option disabled {% if not transactions %}selected{% endif %}>Период</option>
              {% for key in monthDict %}
                <option value="{{key}}" {% if month_filter == key|index_search:0 and year_filter == key|index_search:1 %}selected{% endif %}>{{ monthDict|index_search:key }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="col-lg-2 col-md-5">
            <select class="form-control form-control-sm" name="income_filter_history" id="category-filter__income" onchange="applyActionsAndSubmit([resetExpenseFilter])">
              <option value="" disabled {% if income_category == None %}selected{% endif %}>Категории зачислений</option>
              {% for key in incomeCategoriesDict %}
                <option value="{{key}}" {% if income_category == key %}selected{% endif %}>{{ incomeCategoriesDict|index_search:key }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="col-lg-2 col-md-5">
            <select class="form-control form-control-sm" name="expense_filter_history" id="category-filter__expense" onchange="applyActionsAndSubmit([resetIncomeFilter])();">
              <option value="" disabled {% if expense_category == None %}selected{% endif %}>Категории расходов</option>
              {% for key in expenseCategoriesDict %}
                  <option value="{{key}}" {% if expense_category == key %}selected{% endif %}>{{ expenseCategoriesDict|index_search:key }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="col-lg-2 col-md-5">
            <button class="btn btn-light mt-1" onclick="applyActionsAndSubmit([resetIncomeFilter, resetExpenseFilter])">Сбросить фильтры</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  
  {% if transactions %}
    {% for el in transactions %}
      {% if el.income_category.name %}
        <div class="row justify-content-center row-transaction-history">
          <div class="col-xl-5 col-lg-8 col-md-10">
            <div class="card mt-4">
              <div class="card-header">
                <div class="row">
                  <div class="col-sm">{{ el.account.name }}</div>
                  <div class="col-sm history-date">{{ el.date }}</div>
                </div>
              </div>
              <div class="card-body">
                <div class="row justify-content-around">
                  <div class="col">
                    <fieldset class="reset-this redo-fieldset">
                      <legend class="reset-this redo-legend"> Сумма </legend>
                      <h5 class="card-title  text-center">+{{ el.amount|division:100 }} руб.</h5>
                    </fieldset>    
                  </div>
                  <div class="col">
                    <fieldset class="reset-this redo-fieldset">
                      <legend class="reset-this redo-legend"> Категория </legend>
                      <h5 class="card-title  text-center">{{ el.income_category.name }}</h5>
                    </fieldset>  
                                      
                  </div>
                </div>
                {% if el.commentary %}
                  <div class="row">
                    <div class="col">
                      <fieldset class="reset-this redo-fieldset history-commentary">
                        <legend class="reset-this redo-legend"> Комментарий </legend>
                        <p class="card-text text-center pr-2">{{ el.commentary }}</p>
                      </fieldset>  
                    </div>
                  </div>
                {% endif %}
                <div class="row">
                  <div class="col-md-auto mt-3">
                    <form method="POST" action="{% url 'core:history' %}">
                      {% csrf_token %}
                      <button class="btn btn-danger" type="submit" name="IncomeTransactionId" value="{{el.id}}">Удалить</button>
                      <a class="btn btn-danger"  href="edit/{{el.id}}/IncomeTransaction">Редактировать</a>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endif %}

      {% if el.expense_category.name %}
        <div class="row justify-content-center row-transaction-history">
          <div class="col-xl-5 col-lg-8 col-md-10">
            <div class="card mt-4">
              <div class="card-header">
                <div class="row">
                  <div class="col-sm">{{ el.account.name }}</div>
                  <div class="col-sm history-date">{{ el.date }}</div>
                </div>
              </div>
              <div class="card-body">
                <div class="row justify-content-around">
                  <div class="col">
                    <fieldset class="reset-this redo-fieldset">
                      <legend class="reset-this redo-legend"> Сумма </legend>
                      <h5 class="card-title  text-center">-{{ el.amount|division:100 }} руб.</h5>
                    </fieldset>    
                  </div>
                  <div class="col">
                    <fieldset class="reset-this redo-fieldset">
                      <legend class="reset-this redo-legend"> Категория </legend>
                      <h5 class="card-title  text-center">{{ el.expense_category.name }}</h5>
                    </fieldset>                      
                  </div>
                </div>
                {% if el.commentary %}
                  <div class="row">
                    <div class="col">
                      <fieldset class="reset-this redo-fieldset history-commentary">
                        <legend class="reset-this redo-legend"> Комментарий </legend>
                        <p class="card-text text-center pr-2">{{ el.commentary }}</p>
                      </fieldset>  
                    </div>
                  </div>
                {% endif %}
                <div class="row">
                <div class="col-md-auto mt-3">
                  <form method="POST" action="{% url 'core:history' %}">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit" name="ExpenseTransactionId" value="{{el.id}}">Удалить</button>
                    <a class="btn btn-danger"  href="edit/{{el.id}}/ExpenseTransaction">Редактировать</a>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endif %}

    {% if el.account_to.name %}        
      <div class="row justify-content-center row-transaction-history">          
        <div class="col-xl-5 col-lg-8 col-md-10">            
          <div class="card mt-4">
            <div class="card-header">
              <div class="row">
                <div class="col-sm">{{ el.account_from.name }} -> {{ el.account_to.name }}</div>
                <div class="col-sm history-date">{{ el.date }}</div>
              </div>
            </div>
            <div class="card-body">
              <div class="row justify-content-around">
                <div class="col">
                  <fieldset class="reset-this redo-fieldset inner-amount">
                    <legend class="reset-this redo-legend"> Сумма </legend>
                    <h5 class="card-title text-center mt-2">{{ el.amount|division:100 }} руб.</h5>
                  </fieldset>    
                </div>
                  <div class="col">
                    <fieldset class="reset-this redo-fieldset">
                      <legend class="reset-this redo-legend"> Категория </legend>
                      <h5 class="card-title  text-center">Перевод между своими счетами</h5>
                    </fieldset>                        
                  </div>
                </div>
                
                {% if el.commentary %}
                  <div class="row">
                    <div class="col">
                      <fieldset class="reset-this redo-fieldset history-commentary">
                        <legend class="reset-this redo-legend"> Комментарий </legend>
                        <p class="card-text text-center pr-2">{{ el.commentary }}</p>
                      </fieldset>  
                    </div>
                  </div>
                {% endif %}

                <div class="row">
                  <div class="col-md-auto mt-3">
                    <form method="POST" action="{% url 'core:history' %}">
                      {% csrf_token %}
                      <button class="btn btn-danger" type="submit" name="InnerTransactionId" value="{{el.id}}">Удалить</button>
                      <a class="btn btn-danger"  href="edit/{{el.id}}/InnerTransaction">Редактировать</a>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endif %}

    {% endfor %}
      
  {% else %}
    <p class="text-center text-muted h1 mt-5">Транзакций в текущем месяце нет</p>
  {% endif %}
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/history.js' %}"></script>
{% endblock %}

core/templates/core/test.html
{% extends 'core/base.html' %}

{% block title %}Тестовая страница{% endblock %}

{% block content %}
    {% if account_list %}
        <ul>
        {% for account in account_list %}
            <li>{{ account.name }}</li>
        {% endfor %}
        </ul>    
    {% else %}
        <p>No accounts are available.</p>
    {% endif %}
{% endblock %}